# Generated by Django 2.0.7 on 2018-07-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djoi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(to='djoi.Author'),
        ),
    ]
