# Generated by Django 2.0.7 on 2018-07-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djoi', '0002_auto_20180719_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
    ]
