# Generated by Django 2.0.7 on 2018-07-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djoi', '0003_remove_publication_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(to='djoi.Author'),
        ),
    ]
