# Generated by Django 2.0.7 on 2018-07-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djoi', '0004_publication_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
