# Generated by Django 2.0.7 on 2018-07-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djoi', '0007_auto_20180719_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'verbose_name_plural': 'Aliases'},
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(blank=True, editable=False, to='djoi.Author'),
        ),
    ]
